[package]
name = "warden-engine-napi"
version = "0.1.10"
edition = "2021"
description = "NAPI bindings for the Warden crypto engine"

[lib]
crate-type = ["cdylib"]

[dependencies]
warden-engine = { path = "../warden-engine" }
napi = { version = "3", features = ["napi4"] }
napi-derive = { version = "3", features = ["type-def"] }

[build-dependencies]
napi-build = "2"
